#!/bin/sh

PINGIP="$1"
[ -z "$PINGIP" ] && PINGIP=1.1.1.1
DNSNAME="$2"
[ -z "$DNSNAME" ] && DNSNAME=yahoo.fr

echo monitoring ping to $PINGIP >&2
echo Columns: >&2
echo DATE TIME PING DNS >&2

while true; do
    datetime=$(date '+%Y-%m-%d %H:%M:%S')
    ping "$PINGIP" -c1 > /dev/null
    if [ $? -eq 0 ]; then ping=ok
    else ping=error; fi
    host "$DNSNAME" > /dev/null
    if [ $? -eq 0 ]; then dns=ok
    else dns=error; fi

    echo "$datetime $ping $dns"
    sleep 3
done
