#!/bin/sh

DIR=tmp.d
EXT4=sample.ext4
OVERHEAD_K=100
mkdir $DIR
echo 123 > $DIR/samplefile
echo aaaaaaaaaaaaaaaa-bbbbbbbbbbbbbbbb > $DIR/otherfile

original_size=$(du --block-size=1K $DIR | awk '{print $1}')
size=$(($original_size + $OVERHEAD_K))

echo original_size=$original_size K
echo size=$size K

dd if=/dev/zero of=$EXT4 count=$size bs=1024

/sbin/mkfs.ext4 -F $EXT4 -d $DIR
